export const offlineOrders = [
  {
    Order: {
      ID: 'lebEKhZX90yzgXw7W_vPSw',
      FromUser: {
        ID: 'defaultbuyer',
        CompanyID: 'BAJAJ_Buyer',
        Username: 'defaultbuyer',
        Password: null,
        FirstName: 'default',
        LastName: 'buyer',
        Email: 'bajaj_oc@outlook.com',
        Phone: '5932734694',
        TermsAccepted: null,
        Active: true,
        xp: null,
        AvailableRoles: null,
        Locale: null,
        DateCreated: '2025-05-21T09:57:12.693+00:00',
        LastActive: '2025-06-01T15:32:08.693+00:00',
        PasswordLastSetDate: null,
      },
      FromCompanyID: 'BAJAJ_Buyer',
      ToCompanyID: 'BajajAuto-OC',
      FromUserID: 'defaultbuyer',
      BillingAddressID: null,
      BillingAddress: null,
      ShippingAddressID: null,
      Comments: null,
      LineItemCount: 1,
      Status: 'Open',
      DateCreated: '2025-05-31T14:11:12.84+00:00',
      DateSubmitted: '2025-05-31T14:11:16.017+00:00',
      DateApproved: null,
      DateDeclined: null,
      DateCanceled: null,
      DateCompleted: null,
      LastUpdated: '2025-05-31T14:11:16.743+00:00',
      Subtotal: 125000,
      ShippingCost: 0,
      TaxCost: 0,
      Gratuity: 0,
      Fees: 0,
      PromotionDiscount: 0,
      Currency: null,
      Total: 125000,
      IsSubmitted: true,
      SubscriptionID: null,
      xp: {
        email: 'rvadher@horizontal.com',
      },
    },
    LineItems: [
      {
        ID: 'wi5GKa4bOkuvYjxkJRbS8A',
        ProductID: '85Y5hq-OukeTIGQsf7SuZg',
        Quantity: 1,
        BundleItemID: null,
        IsBundle: false,
        DateAdded: '2025-05-31T14:11:13.417+00:00',
        QuantityShipped: 0,
        UnitPrice: 125000,
        PromotionDiscount: 0,
        LineTotal: 125000,
        LineSubtotal: 125000,
        CostCenter: null,
        DateNeeded: null,
        ShippingAccount: null,
        ShippingAddressID: null,
        ShipFromAddressID: null,
        Product: {
          ID: '85Y5hq-OukeTIGQsf7SuZg',
          Name: 'GoGo P5012',
          Description: null,
          Returnable: false,
          QuantityMultiplier: 1,
          ShipWeight: null,
          ShipHeight: null,
          ShipWidth: null,
          ShipLength: null,
          DefaultSupplierID: null,
          ParentID: null,
          xp: {
            Engine: '124.58 cc',
            MaxTorque: '11 Nm @ 6000 rpm',
            MaxPower: '12 PS @ 8500 rpm',
            Images: [
              {
                Position: 1,
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/bike-listing-page/three-wheeler-page-_-p70.webp',
              },
            ],
            GalleryImages: [
              {
                Url: 'https://www.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/gallery/gallery-webp/image1.webp',
              },
              {
                Url: 'https://www.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/gallery/gallery-webp/image2.webp',
              },
              {
                Url: 'https://www.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/gallery/gallery-webp/image4-new.webp',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/key-features/comfort/extra2.webp',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/three-wheelers/gogo2/key-features/comfort/extra.webp',
              },
            ],
            Gradeability: '27.80%',
            Variant: 'P7012',
            TopSpeed: '50 km/h',
            DriveModes: 'Eco, Power, Climb, Park Assist',
            CertifiedRange: '251 km',
          },
        },
        Variant: null,
        ShippingAddress: null,
        ShipFromAddress: null,
        SupplierID: null,
        InventoryRecordID: null,
        PriceScheduleID: 'GoGo_P5012_Default_Price',
        IsOnSale: false,
        PriceOverridden: false,
        Specs: [],
        IncomingOrderID: null,
        OutgoingOrderID: null,
        InvitationID: null,
        xp: {
          name: 'ravi',
          mobile: 9327346944,
          email: 'rvadher@horizontal.com',
          location: 'vadodara',
          dealer: 'authorized dealer 2',
          buyingPlan: 'within 6 months',
          selectedModel: '',
          selectedColor: '',
        },
      },
    ],
    OrderPromotions: [],
    Subscription: null,
    ShipEstimateResponse: null,
    OrderCalculateResponse: null,
    OrderSubmitResponse: null,
    OrderSubmitForApprovalResponse: null,
    OrderApprovedResponse: null,
    SubscriptionIntegrationResponse: null,
  },
  {
    Order: {
      ID: '9ZJ0p5CXQkKQqIXUoMNe0g',
      FromUser: {
        ID: 'defaultbuyer',
        CompanyID: 'BAJAJ_Buyer',
        Username: 'defaultbuyer',
        Password: null,
        FirstName: 'default',
        LastName: 'buyer',
        Email: 'bajaj_oc@outlook.com',
        Phone: '5932734694',
        TermsAccepted: null,
        Active: true,
        xp: null,
        AvailableRoles: null,
        Locale: null,
        DateCreated: '2025-05-21T09:57:12.693+00:00',
        PasswordLastSetDate: null,
      },
      FromCompanyID: 'BAJAJ_Buyer',
      ToCompanyID: 'BajajAuto-OC',
      FromUserID: 'defaultbuyer',
      BillingAddressID: null,
      BillingAddress: null,
      ShippingAddressID: null,
      Comments: null,
      LineItemCount: 1,
      Status: 'Open',
      DateCreated: '2025-05-31T14:06:15.213+00:00',
      DateSubmitted: '2025-05-31T14:06:18.143+00:00',
      DateApproved: null,
      DateDeclined: null,
      DateCanceled: null,
      DateCompleted: null,
      LastUpdated: '2025-05-31T14:06:19.023+00:00',
      Subtotal: 181317.97,
      ShippingCost: 0,
      TaxCost: 0,
      PromotionDiscount: 0,
      Currency: null,
      Total: 181317.97,
      IsSubmitted: true,
      SubscriptionID: null,
      xp: {
        email: 'rvadher@horizontal.com',
      },
    },
    LineItems: [
      {
        ID: '2c5CkyZmYkKlstG3h_lttA',
        ProductID: 'siY4bFurJUyLh48AwkHkeA',
        Quantity: 1,
        BundleItemID: null,
        IsBundle: false,
        DateAdded: '2025-05-31T14:06:15.78+00:00',
        QuantityShipped: 0,
        UnitPrice: 181317.97,
        PromotionDiscount: 0,
        LineTotal: 181317.97,
        LineSubtotal: 181317.97,
        CostCenter: null,
        DateNeeded: null,
        ShippingAccount: null,
        ShippingAddressID: null,
        ShipFromAddressID: null,
        Product: {
          ID: 'siY4bFurJUyLh48AwkHkeA',
          Name: 'Pulsar NS400z',
          Description: null,
          Returnable: false,
          QuantityMultiplier: 1,
          ShipWeight: null,
          ShipHeight: null,
          ShipWidth: null,
          ShipLength: null,
          DefaultSupplierID: null,
          ParentID: null,
          xp: {
            Engine: '373 cc',
            MaxTorque: '35 Nm @ 6500 rpm',
            MaxPower: '40 PS (29.42 kw) @ 8800 rpm',
            Images: [
              {
                Position: 1,
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/360-degree/360-angles/black-new/00.png',
              },
              {
                Position: 2,
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/web-header-navigator-images/pulsar-ns400z.webp',
              },
            ],
            GalleryImages: [
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/gallery/1.png',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/gallery/2.png',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/gallery/5.png',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/gallery/3.png',
              },
              {
                Url: 'https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-ns400-2024/gallery/4.png',
              },
            ],
            EngineType: 'Liquid Cooled, 4V, DOHC with DLC Coated finger follwers',
            Displacement: '',
            RearSuspension: '43 mm USD',
            FuelTank: '2 L',
            Bullets: [
              'The quintessential traffic cutter motorcycle – Fun. Iconic. Urban ',
              'Sporty Supermotard look with big bike feel',
              'Most Powerful (12 PS) & Fastest in its segment',
              'Most agile bike with best-in-class 198mm ground clearance',
              'Best Power-To-Weight ratio in class with refined power delivery',
              'Exciting new-age colours with digital console',
            ],
          },
        },
        Variant: {
          ID: 'Pulsar_NS400z_BAJAJ_PULSER_SPECS',
          Name: 'Pulsar NS400z BAJAJ PULSER SPECS',
          Description: null,
          ShipWeight: null,
          ShipHeight: null,
          ShipWidth: null,
          ShipLength: null,
          xp: {
            Models: [
              {
                'Pulsar N125 LED Disc': [
                  {
                    colors: [
                      {
                        color: '#FFF',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/mv-pearl-metalic-white.webp',
                      },
                      {
                        color: '#212529',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/mv-ebony-black.webp',
                      },
                      {
                        color: '#dc3545',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/mv-cocktail-wine-red.webp',
                      },
                    ],
                  },
                ],
              },
              {
                'Pulsar N125 LED Disc BT': [
                  {
                    colors: [
                      {
                        color: '#6610f2',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/tv-purple.webp',
                      },
                      {
                        color: '#28a745',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/tv-pewter-grey.webp',
                      },
                      {
                        color: '##90020bd9',
                        Image:
                          'https://www.bajajauto.com/-/media/images/bajaj-auto/booking/pngs-webps/n125/tv-ebony-black--cocktail-wine.webp',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
        ShippingAddress: null,
        ShipFromAddress: null,
        SupplierID: null,
        InventoryRecordID: null,
        PriceScheduleID: 'Pulsar_NS',
        IsOnSale: false,
        PriceOverridden: false,
        Specs: [
          {
            SpecID: 'BAJAJ_PULSER_SPECS',
            Name: 'BAJAJ PULSER SPECS',
            OptionID: 'BAJAJ_PULSER_SPECS_N',
            Value: 'N',
            PriceMarkupType: 'NoMarkup',
            PriceMarkup: null,
          },
        ],
        IncomingOrderID: null,
        OutgoingOrderID: null,
        InvitationID: null,
        xp: {
          name: 'ravi',
          mobile: 9327346944,
          email: 'rvadher@horizontal.com',
          location: 'vadodara',
          dealer: 'authorized dealer 3',
          buyingPlan: 'within 6 months',
          selectedModel: 'pulsar n125 led disc bt',
          selectedColor: '##90020bd9',
        },
      },
    ],
    OrderPromotions: [],
    Subscription: null,
    ShipEstimateResponse: null,
    OrderCalculateResponse: null,
    OrderSubmitResponse: null,
    OrderSubmitForApprovalResponse: null,
    OrderApprovedResponse: null,
    SubscriptionIntegrationResponse: null,
  },
]
